### ISSUE TITLE
Unable to see the html page on Mac 10.7.3

### ISSUE THREAD

**Issue by vnandini** [lobobrowser/LoboBrowser#1]
Hi,

I have a java application which uses lobo browser to render the html page in a jframe.This application is run on Mac OS X 10.7.3.Jre version used is 1.7 update 80(oracle jre). With this jre version, iam unable to see the html page.Its blank.With apple Java 1.6, it works fine.

Same application works fine on Mac OS X 10.8, 10.9 and 10.10 with the same jre version - 1.7.

Is this a bug in lobo browser or JRE 1.7or Mac OS X?
Please suggest a fix/workaround for this issue.

**Comment by xaoseric** [comment]
yes, it is a bug. The cobra rendering engine has been updated however to work properly https://github.com/lobobrowser/Cobra

**Comment by xaoseric** [comment]
This has been fixed
