### ISSUE TITLE
Is project already functional ?

### ISSUE THREAD

**Issue by jourquin** [lobobrowser/LoboBrowser#2]
Hi,
I've successfully created the LoboBrowser-1.0-SNAPSHOT.jar (after having created the cobra jar) and tried to run LoboMain after having put "primary.jar" in an "ext" directory. The browser is displayed and I don't see any error (I've used "-debug" as an argument to the main() method and put slf4j-simple.jar in the class path. Logging seems to work as I see the jOOQ output). However, nothing is rendered in the main frame, although, at the bottom left of the browser, I see "processed http://NameOfTheWebSiteITryToDisplay".

This was tested on Mac and Linux.

Did I miss something ? What is the role of jStyleDomBridge and jSoup that are forked in the lobobrowser repository on GitHub ? Do I need them ?

**Comment by xaoseric** [comment]
Hi there,
At the moment it should work. However, the way Cobra and the way LoboBrowser are created, most of the gui functionality is in Cobra. I am currently working on moving the gui functionality away from cobra and to the main lobobrowser package. I am also experimenting with a possible koltin rewrite.

**Comment by xaoseric** [comment]
These issues have been fixed in the latest commit.
